---
- name: Restart odoo
  community.docker.docker_compose_v2:
    project_src: "{{ apps_root }}/odoo"
    state: present
    recreate: always
    pull: always
  become: true
  become_user: "{{ deploy_user }}"
